### ISSUE TITLE
[Bug] The Version 3.4.1PE of Docker Image of TB-Integration-Executor is not available at Docker Hub. 

### ISSUE THREAD

**Issue by cGlybWlu** [thingsboard/thingsboard-pe-docker-compose#37]
Like written down in the Title: 
The Version 3.4.2PE of the Docker Image of TB_Integration-Executor is not available at Docker Hub.

Workaround:
Change/Hardcode the Version (3.4.0PE) in docker-compose.yml

**Comment by pon0marev** [comment]
The tb-pe-integration-executor version 3.4.1 was indeed unavailable on the docker hub for a while. However, this was fixed within a few days.
